export const STACK_LOGIN= "STACK_LOGIN";
export const STACK_CONTACT = "STACK_CONTACT";
export const STACK_STORY = "STACK_STORY";
export const STACK_STORYPOINT = "STACK_STORYPOINT";
export const STACK_RESOURCES = "STACK_RESOURCES";

