export const CONTACT_LIST_UPDATED = "CONTACT_LIST_UPDATED";
export const STORY_LIST_UPDATED = "STORY_LIST_UPDATED";
export const STORYPOINT_LIST_UPDATED = "STORYPOINT_LIST_UPDATED";
export const RESOURCES_LIST_UPDATED = "RESOURCES_LIST_UPDATED";
